name: Main branch and PR build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extra: [ none, errorprone ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Maven install
        run: mvn -B -Dextra=${{ matrix.extra }} install
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ~/.m2/repository/io/disquark/immutables/**
          if-no-files-found: error
          retention-days: 1