name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.repository == 'cottoncammy/immutables'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Maven release
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |  
          echo "${{ secrets.GPG_SECRET_KEY }}" | base64 --decode | gpg2 --batch --import 
          mvn -B -s .github/mvn-ci-settings.xml -ntp -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} -Prelease deploy